config/routes.rb
Rails.application.routes.draw do

  # devise_for :users
  # resources :posts
  resources :fruits
  # resources :animals
  # resources :books
  # resources :news

  get '/all_values', to: 'fruits#all_values'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord
  serialize :song_id, Array
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/car.rb
class Car < ApplicationRecord
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/models/fruit.rb
class Fruit < ApplicationRecord
end

app/models/full_calendar_engine.rb
class FullCalendarEngine < ApplicationRecord
  belongs_to :site
end

app/models/news.rb
class News < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/site.rb
class Site < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        flash[:tutorial] = 'hallo!'
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:model, :kilometers, :year, :color, :price)
    end
end

app/controllers/fruits_controller.rb
class FruitsController < ApplicationController
  before_action :set_fruit, only: [:show, :edit, :update, :destroy]

  # GET /fruits
  # GET /fruits.json
  def index
    @bla = 'bla'
    @fruits = Fruit.order(:id).page(params[:page]).per(5)
    @book = Book.new
    respond_to :html, :js
  end

  def all_values
    @bla = 'meh'
    @fruits = Fruit.order(:id).page(params[:page]).per(10)
    respond_to :html, :js
  end

  # GET /fruits/1
  # GET /fruits/1.json
  def show
  end

  # GET /fruits/new
  def new
    @fruit = Fruit.new
  end

  # GET /fruits/1/edit
  def edit
  end

  # POST /fruits
  # POST /fruits.json
  def create
    @fruit = Fruit.new(fruit_params)

    respond_to do |format|
      if @fruit.save
        format.html { redirect_to @fruit, notice: 'Fruit was successfully created.' }
        format.json { render :show, status: :created, location: @fruit }
      else
        format.html { render :new }
        format.json { render json: @fruit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fruits/1
  # PATCH/PUT /fruits/1.json
  def update
    respond_to do |format|
      if @fruit.update(fruit_params)
        format.html { redirect_to @fruit, notice: 'Fruit was successfully updated.' }
        format.json { render :show, status: :ok, location: @fruit }
      else
        format.html { render :edit }
        format.json { render json: @fruit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fruits/1
  # DELETE /fruits/1.json
  def destroy
    @fruit.destroy
    respond_to do |format|
      format.html { redirect_to fruits_url, notice: 'Fruit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fruit
      @fruit = Fruit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fruit_params
      params.require(:fruit).permit(:name)
    end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  # GET /news
  # GET /news.json
  def index
    @news = News.all
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:title)
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/fruits_helper.rb
module FruitsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/fruits/_form.html.erb
<%= form_for(fruit) do |f| %>
  <% if fruit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fruit.errors.count, "error") %> prohibited this fruit from being saved:</h2>

      <ul>
      <% fruit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fruits/all_values.js.erb
$('#pagination').html('<%= escape_javascript( paginate @fruits ) %>')
$('#example').html('<%= escape_javascript( @bla ) %>')

app/views/fruits/edit.html.erb
<h1>Editing Fruit</h1>

<%= render 'form', fruit: @fruit %>

<%= link_to 'Show', @fruit %> |
<%= link_to 'Back', fruits_path %>

app/views/fruits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fruits</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fruits.each do |fruit| %>
      <%= fruit.name %><br>
    <% end %>
  </tbody>
</table>

<div id="pagination"></div>
<div id="example"></div>

<br>

<div id="change_pagination">
  <a href="#">Press me please</a>
</div>

<script>
  $(document).ready(function(e) {
    $.ajax({
      url: '/fruits',
      dataType: 'script'
    })
  });

  $('#change_pagination a').click(function(e) {
    e.preventDefault();
    $.ajax({
      url: '/all_values',
      dataType: 'script',
    })
  });
</script>

app/views/fruits/index.js.erb
$('#pagination').html('<%= escape_javascript( paginate @fruits ) %>')
$('#example').html('<%= escape_javascript( @bla ) %>')

app/views/fruits/new.html.erb
<h1>New Fruit</h1>

<%= render 'form', fruit: @fruit %>

<%= link_to 'Back', fruits_path %>

app/views/fruits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @fruit.name %>
</p>

<%= link_to 'Edit', edit_fruit_path(@fruit) %> |
<%= link_to 'Back', fruits_path %>